### ISSUE TITLE
regarding the .env file

### ISSUE THREAD

**Issue by sarja830** [mohamedsamara/mern-ecommerce#1]
how to set the values of
PORT & BASE_SERVER_URL & BASE_API_URL & BASE_CLIENT_URL.

i am running the app on localhost.

i want the app to run on http://localhost:3000/ (frontend)
and the api call to be answered from 5000 (backend)

what value of base client url to be used??
i am getting error 404 not found 
please help me out thanks in advance

**Comment by mohamedsamara** [comment]
@sarja830 I think with the current implementation of using [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) on the server, you probably have to install a proxy to make the backend run on a different port. This is a proxy for node [node-http-proxy](https://github.com/http-party/node-http-proxy)

Right now both the client and the server are running on the same port and host, like this:
BASE_CLIENT_URL=http://localhost:5000
BASE_SERVER_URL=http://localhost:5000
PORT=5000

**Comment by kmbawuike** [comment]
@mohamedsamara nice implementation of the MERN stack. I am currently learning and studying this project has helped me a lot.
what did you use as the BASE_API_URL

**Comment by mohamedsamara** [comment]
@kmbawuike Thanks, I'm glad it helped you! I've used it like this BASE_API_URL=api. I updated the code and added .env.example file.
