### ISSUE TITLE
Fetch brand API throwing 400 bad request error

### ISSUE THREAD

**Issue by akash-2095** [mohamedsamara/mern-ecommerce#104]
Can anyone help me with the configurations? I'm a beginner trying to understand the full stack system.
- I don't see the end points for these APIs and wanted to understand how the mongoose connection was working?
- Why is the Brand and Product fetching API call failing for me in my local environment but category and other APIs are working?

**Comment by hamza4707** [comment]
@akash-2095 what's the solution of this problem? I'm also facing the same issue
