### ISSUE TITLE
No online user found at the admin support tab on dashboard after sending support message by a user/customer.

### ISSUE THREAD

**Issue by smartupnish** [mohamedsamara/mern-ecommerce#105]
**No online user found at the admin support tab on the dashboard after sending support message by a user/customer**
Support functionality is not working expected as online users are not shown at the admin dashboard.

**To Reproduce**
1. Go to the 'Support tab from the admin side' by login to the admin account
2. Go to the 'Support tab from the user/customer side' by login in as a user with a different machine/browser.
3. User - Send test from the support section to the admin.
4. Admin - Admin verifies the online users at the support tab of the dashboard.

**Expected behavior**
Admin should see the online users and be able to text them back at the support tab of the dashboard.

**Screenshots**
User/Customer (Able to send query successfully)
![image](https://user-images.githubusercontent.com/64981592/142370555-dde007f1-72ce-4ce4-8118-a93ed97125c7.png)
Admin **(Unable to see the online users and text sent by the customer)**
![image](https://user-images.githubusercontent.com/64981592/142370695-2797b2e5-2f97-4c72-9e7d-4a3bbf49a839.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [Version 95.0.4638.69 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [OnePlus 3T A3003]
 - OS: [Android]
 - Browser [Chrome]
 - Version [OxygenOS - 9.0.6]

**Comment by mohamedsamara** [comment]
Hey @karthikeyana! can you please check this issue? I know you know more about this feature. Thanks!

**Comment by karthikeyana** [comment]
Sure @mohamedsamara  Will have a look.

**Comment by karthikeyana** [comment]
For the Same Network and different browsers within the system, it works expected behaviour. @smartupnish  give me some more details please.

**Comment by smartupnish** [comment]
@karthikeyana Could you please tell me what kind of extra details you expect from me? I tried it on a different network and browser, and it did not behave as expected.

**Comment by karthikeyana** [comment]
@smartupnish https://join.skype.com/invite/ccOXCw31kMWS this is my skype id, ping me we can discuss.

**Comment by karthikeyana** [comment]
Hi @smartupnish, For me working fine in Heroku deployment 

URL: https://mern-store-80201.herokuapp.com/

Admin Credential:
user name: tfs123@yopmail.com
password: tfs123

User Credential:
user name: tfs@yopmail.com
password: tfs123

Please use the above credentials to validate the support functionality. If you have doubts please let me know. If the functionality works the expected way please close the ticket.

Thanks.

**Comment by smartupnish** [comment]
Thanks, @karthikeyana This is working as expected. Now, Admin is able to see the online user and able to chat with the member/merchant.
