### ISSUE TITLE
Styling support chat 

### ISSUE THREAD

**Issue by mohamedsamara** [mohamedsamara/mern-ecommerce#107]
* Support tab in account page needs styling that matches the rest of the website theme.

**Comment by mohamedsamara** [comment]
<img width="1228" alt="user" src="https://user-images.githubusercontent.com/45723974/142781529-d5905c50-180c-42c5-8fea-375afcbcae4c.png">
<img width="1228" alt="admin" src="https://user-images.githubusercontent.com/45723974/142781532-e6933bb2-00e2-40a6-97b7-67af4921b54b.png">

**Comment by mohamedsamara** [comment]
@karthikeyana  Can you check this one please? After I deployed I noticed the styling are a bit off. Let's make it match the other components theme.

**Comment by karthikeyana** [comment]
Hi @mohamedsamara.,

I have improved the Support Feature styling UI component please review the same and let me know if any further changes are required.

**Pull Request:** Support Feature UI Improvement done #112

User Account:

![image](https://user-images.githubusercontent.com/10651426/143470283-e076595a-e8b9-4690-96a8-2906656cec55.png)

Admin Account:

![image](https://user-images.githubusercontent.com/10651426/143470577-2892a314-76a5-4a79-ab60-27552bbbe744.png)
