### ISSUE TITLE
Feature Enhancement Done: Enable Admins and Merchants to upload product image

### ISSUE THREAD

**Issue by karthikeyana** [mohamedsamara/mern-ecommerce#11]
```
Hi Mohamedsamara.,
   
     Happy to Chat with you., This project is very much helpful to every who working on E-Commerce projects and MERN Stack Developers and More interesting to everyone. I have Based on your What's Next: features I have implemented **Enable Admins and Merchants to upload product images** Feature on front and backend by followed by your code [**Attached Screens**]. if you find useful you review and merge with your existing code and I'm willing to contribute to this project with further updates and feature enhancement things if you are fine. For more details, you share your mail/chat id. 
```

Files worked/update
![image](https://user-images.githubusercontent.com/10651426/98449892-c4102680-215d-11eb-92b3-04396f1d5cb0.png)

Thanks.
Karthikeyan

![image](https://user-images.githubusercontent.com/10651426/98449563-907fcd00-215a-11eb-8e68-cea2701bfaea.png)
![image](https://user-images.githubusercontent.com/10651426/98449596-c58c1f80-215a-11eb-9274-aad8ca35504b.png)
![image](https://user-images.githubusercontent.com/10651426/98449606-dccb0d00-215a-11eb-9a14-91530d8d0737.png)
![image](https://user-images.githubusercontent.com/10651426/98449623-fcfacc00-215a-11eb-91d1-6bccc77df254.png)
![image](https://user-images.githubusercontent.com/10651426/98449637-169c1380-215b-11eb-92d8-c83069a0739c.png)
![image](https://user-images.githubusercontent.com/10651426/98449660-4519ee80-215b-11eb-83fa-38e21120a3b6.png)

**Comment by mohamedsamara** [comment]
Hi @karthikeyana, I'm glad this project helps and thanks for the contribution. 'll take a look in the next two days and see how we can merge this.
