### ISSUE TITLE
Products not shown in product page

### ISSUE THREAD

**Issue by kainatkiranrashid2** [mohamedsamara/mern-ecommerce#122]
Hello , Mohammad Samara,
I have added few products, but these are not shown when i click shop Pls check and help me get the solution,

Thanks
![image](https://user-images.githubusercontent.com/97904362/155393090-bc08633d-af7a-4716-88a0-3033313922b2.png)

![image](https://user-images.githubusercontent.com/97904362/155392668-b0dc9ba2-4eed-46b2-b348-b04fd95e5d38.png)

**Comment by mohamedsamara** [comment]
@kainatkiranrashid2 make sure the product is active. From the sidebar products, click on any product to edit and change "is active" field to active so that it appears on the shop.

**Comment by kainatkiranrashid2** [comment]
It is active, but still does not show up

**Comment by mohamedsamara** [comment]
Try to add brand and assign the product to the brand and see if it shows up, make sure  brand is active. There is a chance it is not pulling products with no brands.

**Comment by kainatkiranrashid2** [comment]
Brands products are shown in brands, but when i click shop , they do not show their as well

**Comment by smartupnish** [comment]
@kainatkiranrashid2 Seems like you have added a price of more than $500. Due to which filters are restricting it to show you. You can remove the hard-coded part from the code and assign the largest price of products in the filters.

**Comment by mohamedsamara** [comment]
@kainatkiranrashid2 please make sure the product is assigned to a brand or they won't appear in the shop.

**Comment by Mugerwa-Joseph** [comment]
> @kainatkiranrashid2 Seems like you have added a price of more than $500. Due to which filters are restricting it to show you. You can remove the hard-coded part from the code and assign the largest price of products in the filters.

Perfect, Thanks for the fix, I was worried as well.
Just look for the range slider component under client/app/components/common/RangeSlider and change the maximum value to cater for your needs.

**Comment by hamza4707** [comment]
Products are not shown in SHOP ,all are assigned to brand and with in the the price range but cant see in brands or shop and every product is active as well

**Comment by mohamedsamara** [comment]
Closing this issue. If the products are shown or not, it depends on the filters passed along with the request like the price range for example. However the the API works as expected.
