### ISSUE TITLE
merchant not received order details

### ISSUE THREAD

**Issue by errorLAD** [mohamedsamara/mern-ecommerce#125]
order details is not received

**Comment by kainatkiranrashid2** [comment]
I am faceing the same problem @mohamedsamara could you pls guide

**Comment by mohamedsamara** [comment]
@errorLAD @kainatkiranrashid2 can you please provide more information on the issue?

**Comment by mohamedsamara** [comment]
There is no enough information in this issue. If this is a feature request for Merchants to see customer orders, I'm creating a separate issue detailing the Feature request.
