### ISSUE TITLE
Unable to login admin with the given credentials 

### ISSUE THREAD

**Issue by manisha1994-coder** [mohamedsamara/mern-ecommerce#127]
I login with the provided credentials tfs123@yopmail.com but i was unable to login. 

Can you help me in logging in admin panel .

**Comment by mohamedsamara** [comment]
@manisha1994-coder did you try to reset password? An email will be sent to your email, open it and follow the link to reset and create new password.

**Comment by manisha1994-coder** [comment]
I did not receive any mail, also when I'm logging in with this credentials ID: tfs123@yopmail.com and pwd: tfs123 to access the admin side it is throwing error(user not found).

Pls help me to access the admin side.

**Comment by mohamedsamara** [comment]
@manisha1994-coder if it says "user not found", it means there is no record in database for this email. Are you getting this error on your local machine? and did you connect your own database? If yes, please try to sign up instead and see if there is any errors.

**Comment by 127001sudais** [comment]
> I login with the provided credentials [tfs123@yopmail.com](mailto:tfs123@yopmail.com) but i was unable to login.
> 
> Can you help me in logging in admin panel .

you can go in your db and then change your user to "ROLE_ADMIN" if you are developing the app

**Comment by mohamedsamara** [comment]
There is a guide on adding an admin user with this [guide](https://github.com/mohamedsamara/mern-ecommerce#database-seed) now. Closing this issue.
