### ISSUE TITLE
Can't create other users

### ISSUE THREAD

**Issue by Mugerwa-Joseph** [mohamedsamara/mern-ecommerce#131]
After creating the first user, the system is not allowing creation of other users.
What could be the cause?

**Comment by mohamedsamara** [comment]
@Mugerwa-Joseph are you referring to the seed database logic?

**Comment by Mugerwa-Joseph** [comment]
**@mohamedsamara** Yes, how can I get over that?

**Comment by mohamedsamara** [comment]
@Mugerwa-Joseph you can pass different email as an argument. [Guide](https://github.com/mohamedsamara/mern-ecommerce#database-seed)
