### ISSUE TITLE
Discussion / Clarification - Please do spend time to respond.

### ISSUE THREAD

**Issue by vissharm** [mohamedsamara/mern-ecommerce#132]
Question is related to below entries of config/env file. Please answer inline.

  * MONGO_URI & JWT_SECRET - **I hope we could give any JWT string secret key. Yes/No ?**
  * PORT & BASE_SERVER_URL & BASE_API_URL & BASE_CLIENT_URL - **Hosting everything together at one server (backend and frontend) is secure ? Or we could deploy separately also?**
  * MAILCHIMP_KEY & MAILCHIMP_LIST_KEY => Mailchimp configuration **I hope free tier features of mailchimp would work with app without error?**
  * MAILGUN_KEY & MAILGUN_DOMAIN & MAILGUN_EMAIL_SENDER => Mailgun configuration **What this do ? We already have mailchimp service used above ? Any free-tier available alternatives of this which could be used easily with minimum changes in existing code?**
  * GOOGLE_CLIENT_ID & GOOGLE_CLIENT_SECRET & GOOGLE_CALLBACK_URL => Google Auth configuration **I hope this is additional ? We could integrate own authentication from application database or that is also available with code?**
  * FACEBOOK_CLIENT_ID & FACEBOOK_CLIENT_SECRET & FACEBOOK_CALLBACK_URL => Facebook Auth configuration - **I hope this is additional ? We could integrate own authentication from application database?**
  * AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY & AWS_REGION & AWS_BUCKET_NAME => AWS configuration **Is this mandatory ? Code cannot be deployed without cloud i.e. on normal server?**
  
  
  **Do we have any default text/csv data or dummy database with admin and normal user login data to explore all the forms and fields in app with sample data ?**

**Comment by vissharm** [comment]
@mohamedsamara Could you please reply on this?

**Comment by mohamedsamara** [comment]
Hi @vissharm! I apologize for my late reply, I was buried in work. Here are my answers to you questions:


JWT_SECRET: You can run the following command to generate one 
```
node -e "console.log(require('crypto').randomBytes(256).toString('base64'));"
```
PORT & BASE_SERVER_URL & BASE_API_URL & BASE_CLIENT_URL: I haven't tried to separate frontend/backend, you need to do extra work to do it. This project is an example of using both in the same repo

MAILCHIMP_KEY & MAILCHIMP_LIST_KEY: For the amount of current usage, it's working without errors.

MAILGUN_KEY & MAILGUN_DOMAIN & MAILGUN_EMAIL_SENDER: Same as MAILCHIMP. I'm using the free tier sandbox.

GOOGLE_CLIENT_ID & GOOGLE_CLIENT_SECRET & GOOGLE_CALLBACK_URL: This is opt-in and you can replace it from the code.

FACEBOOK_CLIENT_ID & FACEBOOK_CLIENT_SECRET & FACEBOOK_CALLBACK_URL: Same as Google

AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY & AWS_REGION & AWS_BUCKET_NAME: This is used for uploading product images and other things in the future.

Generally, these services can be replaced with anything you would like to integrate instead. The project only requires the following:

1. MONGO_URI
2. JWT_SECRET: generate with the above command
3. PORT (already in env example)
4. BASE_CLIENT_URL (already in env example)
5. BASE_SERVER_URL (already in env example)
6. BASE_API_URL (already in env example)

Currently, there is only seed data functionality that adds an admin user to the database. Here is the [guide](https://github.com/mohamedsamara/mern-ecommerce#database-seed). 

Also, created a [PR](https://github.com/mohamedsamara/mern-ecommerce/issues/137) for the seed and dummy data feature.


I hope that answers your questions,
Mohamed

**Comment by vissharm** [comment]
Thanks
