### ISSUE TITLE
Add dummy data with seed functionality for Products, Brands, Categories

### ISSUE THREAD

**Issue by mohamedsamara** [mohamedsamara/mern-ecommerce#137]
* Add the ability to run a script to populate the database with dummy ecommerce data including brands, products, categories

**Comment by buddhathemanoj** [comment]
when i try to add dummy data i am getting seed db started but, data is not being added to mongodb , what i am doing wrong ?

**Comment by Tushar260603** [comment]
"data:import": "node seeder.js"  


use this in scripts in package.json file in backend

**Comment by petecheslock** [comment]
Hi @mohamedsamara I've attached a PR with changes to seed the DB with sample data using `faker`
