### ISSUE TITLE
Why do we need all the keys to run the project?

### ISSUE THREAD

**Issue by 70shakeel** [mohamedsamara/mern-ecommerce#15]
I have been trying to run the project on my machine and it is not compiling without all the keys.

**Comment by mohamedsamara** [comment]
@70shakeel AWS keys were missing. I updated .env.example with all the keys required to run the project.

**Comment by iarobinson** [comment]
@mohamedsamara - FYI - When I cloned the repository, I still have to add `none` to mailchimp and mailgun keys in order for the app to run. I also need to comment out a lot of the logic for MailChimp.

Then I'm running into the following error:
```
/Users/silverSheep/Desktop/mern-ecommerce/server/routes/api/product.js:32
    if (!productDoc || (productDoc && productDoc?.brand?.isActive === false)) {
                                                 ^

SyntaxError: Unexpected token '.'
```

This looks like maybe my database needs to be seeded....

**Comment by mohamedsamara** [comment]
Thanks @iarobinson! There is a fix merged to handle missing keys error, it will no longer throw an error and the website should run without the keys. The second error you posted I wasn't able to reproduce yet but I would also say the database needs to be seeded. However, I still want to reproduce it so it does not throw this error.
