### ISSUE TITLE
[Refactoring] Add/Edit forms seems to be duplicate. Could reuse fields with editable capability controlled by flag if required.

### ISSUE THREAD

**Issue by vissharm** [mohamedsamara/mern-ecommerce#155]
Add/Edit forms seems to be duplicate. Could reuse fields with editable capability controlled by flag if required.

**Comment by mohamedsamara** [comment]
Thank you for the suggestion. We are reusing the Form small components (Inputs and Dropdowns, and Buttons) and kept Forms for Add an Edit separate to maintain a clean way to further develop the forms in the future. I'm closing this as it's not a high priority at the moment.
