### ISSUE TITLE
[Incomplete product collection design] Cart items are not persisted to database. It's only persisted post placing order.

### ISSUE THREAD

**Issue by vissharm** [mohamedsamara/mern-ecommerce#158]
Product collection design looks incomplete. Cart table should be populated asap user add item to bag and delete item from table if user remove item from cart. If browser is reopened or cache cleared, the cart section should be able to fetch items from database based on user login.

**Comment by vissharm** [comment]
Also, do we need to maintain user sessions in database.... ecommerce dbs do that.... what would be its significance ? not sure.

**Comment by mohamedsamara** [comment]
Thank you, great suggestions. Not sure if we need it at the moment but I think the current design flow works just fine for the cart.
