### ISSUE TITLE
Can't Upload image

### ISSUE THREAD

**Issue by devogi** [mohamedsamara/mern-ecommerce#159]
When I try to add Product image from add product page, it gives Error.
Also I didnt Add AWS key yet. İs it necessary?
![Screenshot_265](https://user-images.githubusercontent.com/75084633/173357179-4581bac3-b09c-434f-8f33-41f19290217a.png)

**Comment by mohamedsamara** [comment]
@devogi yes! the uploading image code is using AWS S3.

**Comment by mohamedsamara** [comment]
@devogi most likely, I don't think the add product has issues, it has to be about missing AWS keys.

**Comment by mohamedsamara** [comment]
@devogi closing this issue as discussed. This is just a missing AWS env variable. Once the env variable is added or the code to upload the image is removed - opted out there will be no issue.
