### ISSUE TITLE
Possible issues with webpack/procfile

### ISSUE THREAD

**Issue by frontend56** [mohamedsamara/mern-ecommerce#160]
I'm trying to deploy the app on heroku but I'm getting these errors:
 1- Failed to load ./.env.
2- at=error code=H10 desc="App crashed" method=GET path="/"
3-at=error code=H10 desc="App crashed" method=GET path="/favicon.ico"

**Comment by mohamedsamara** [comment]
@frontend56 did you change any of the package.json [scripts](https://github.com/mohamedsamara/mern-ecommerce/blob/master/package.json#L13) or the [Procfile](https://github.com/mohamedsamara/mern-ecommerce/blob/master/Procfile)? You need to add the env variables - same ones in the .env.example to the Heroku project settings.
 
<img width="862" alt="Screen Shot 2022-07-05 at 2 09 58 PM" src="https://user-images.githubusercontent.com/45723974/177416937-d2db607a-3674-4f36-b523-2b72f87243d2.png">
