### ISSUE TITLE
The client side script is not fetching locally??

### ISSUE THREAD

**Issue by miidlaj** [mohamedsamara/mern-ecommerce#163]
I have deleted the client folder completely a still fetching the UI. I dont know from where it is executing. So I cant edit in design.
Someone please help me 
![Capture2](https://user-images.githubusercontent.com/70736601/177006510-9dd8fb3c-0373-4d6a-b384-214065b1bcea.JPG)
![Capture](https://user-images.githubusercontent.com/70736601/177006513-f3323e98-3663-4ece-8040-1e1008f6b3d2.JPG)
.

**Comment by mohamedsamara** [comment]
@midlaj4466 sorry for the late reply. Did you change anything in the package.json script? if you deleted the client directory and this still running, then it is possible that it is reading from the dist directory and the script you ran was `npm run build` and `npm start` afterwards. These two script commands is to create a build and preview the build. If you are working on a dev environment you will be running `npm run dev` instead where you can make the updates to the client directory. I couldn't find any other possibilities of what's happening. Also I believe the PORT in the env.example was 3000 not 5000 maybe try re-clone the repo again and run it as is. Please let me know if you still face the issue.
