### ISSUE TITLE
Not able to add products

### ISSUE THREAD

**Issue by Pranavan756** [mohamedsamara/mern-ecommerce#169]
I tried to add products but it says error. Even with the correct sku number it is still incorrect. I think its a bug.

**Comment by mohamedsamara** [comment]
@Pranavan756 Sorry for the late reply. Please share more information of the logs if there are any or a screen recording on how to reproduce the bug.

**Comment by mohamedsamara** [comment]
Closing this. There is no enough information about the issue.
