### ISSUE TITLE
How do you change the currency symbol?

### ISSUE THREAD

**Issue by dvbst** [mohamedsamara/mern-ecommerce#170]
Hello, Can you tell me how to change the  '$' currency symbol to another?

**Comment by yakupyazicioglu** [comment]
Hi @dvbst 
Unfortunately, you should do it manually by searching the '$' symbol which there is a lot. 
My suggestion is to add `export const CURRENCY = "SEK";` line somewhere and use it whenever necessary. 
One of the lines I found quickly: `<p className="price mb-0">${product.price}</p>` in ProductList/index.js.
