### ISSUE TITLE
Change shipping text

### ISSUE THREAD

**Issue by mohamedsamara** [mohamedsamara/mern-ecommerce#179]
On checkout popup -> shipping should be like:
Label       -----> Value
Shipping  -----> Free (For now - no charge)

**Comment by JawHawk** [comment]
Can you pl share the ss where this change should be done ?

**Comment by mohamedsamara** [comment]
Thanks @JawHawk! This is where the change, the label and value of shipping should be like this:

Label -----> Value
Shipping -----> Free (For now - no charge)

<img width="469" alt="Screen Shot 2022-12-25 at 1 51 49 PM" src="https://user-images.githubusercontent.com/45723974/209482826-1bf88ef1-8b21-4dc8-9835-16c239072121.png">

**Comment by ShanifKn** [comment]
is this still pending  ?

**Comment by Anabil-Baruah** [comment]
Is this issue fixed or its still pending ?

**Comment by mohamedsamara** [comment]
@ShanifKn @Anabil-Baruah Yes. This is to replace the shipping label and text to this:  Shipping -----> Free.

**Comment by Anabil-Baruah** [comment]
@mohamedsamara  I can do . I will create a PR ASAP

**Comment by Anabil-Baruah** [comment]
> @ShanifKn @Anabil-Baruah Yes. This is to replace the shipping label and text to this:  Shipping -----> Free.

Ok I'll create a PR ASAP

**Comment by mohamedsamara** [comment]
@Anabil-Baruah Perfect, thank you!

**Comment by NehaNihar12** [comment]
I see this issue is still open. I'll resolve and raise a PR for it.

**Comment by NehaNihar12** [comment]
Done. https://github.com/mohamedsamara/mern-ecommerce/pull/215.
