### ISSUE TITLE
Unable to add review for a non recommended product

### ISSUE THREAD

**Issue by faraz16iqbal** [mohamedsamara/mern-ecommerce#194]
**Describe the bug**
While adding a review and selecting "No" for on the _Will you recommend this product?_ field results in a 400 due to small issue in the DOMPurify sanitize function.

**To Reproduce**
1. Sign In and select any product
2. Fill all the values in the _Add Review_ form and select "No" on the _Will you recommend this product?_ field.
3. See error

**Expected behavior**
A successful request to the server.

**Comment by faraz16iqbal** [comment]
I already have the fix for this bug, can I go ahead and resolve it?

**Comment by mohamedsamara** [comment]
@faraz16iqbal Off course! Please do and i will review and merge. Thanks!

**Comment by rahulll18** [comment]
Kindly assign this issue to me. I will try my best to resolve this isuue
