### ISSUE TITLE
pagination not works properly

### ISSUE THREAD

**Issue by FarhangQ** [mohamedsamara/mern-ecommerce#197]
for ex. https://mern-store.onrender.com/shop/brand/gucci when you change sort, all products fecth again. in other hand some times, show up only one item but pagination still there and when you paginate to other, all products show up again

**Comment by abhisheksharma886** [comment]
Kindly assign this issue to me, and I will diligently work to deliver a swift and effective solution.

**Comment by rahulll18** [comment]
Please assign this isue to me. I will try to resolve this issue
