### ISSUE TITLE
Search Bar not working

### ISSUE THREAD

**Issue by Aizazahmed-7** [mohamedsamara/mern-ecommerce#199]
**Describe the bug**

The search bar is not working

**Expected behavior**
Thes Search bar should toke us to a search page

assign this task to me i can do this

**Comment by mohamedsamara** [comment]
Hi @Aizazahmed-7! thanks for sharing! Can you please explain more? The current search bar is working, test by typing "test product" for example - it acts more like an autocomplete right now. If you're suggesting a new page for searching as a new feature, can you please describe the UI behavior a little more and what happen when i click or start typing in the search bar? I'd be happy to discuss and see if we can improve it.

Thanks!
Mohamed

**Comment by abhisheksharma886** [comment]
Kindly assign this issue to me, and I will diligently work to deliver a swift and effective solution.

**Comment by rahulll18** [comment]
Kindly assign this issue to me.So this issue can be resolved effectively

**Comment by chandra1899** [comment]
is this issue still open , can i work on this.

**Comment by donoftime2018** [comment]
I'd like to work on this issue

**Comment by mohamedsamara** [comment]
Closing this. There is no enough details about if there is an issue. Explained above.

> Hi @Aizazahmed-7! thanks for sharing! Can you please explain more? The current search bar is working, test by typing "test product" for example - it acts more like an autocomplete right now. If you're suggesting a new page for searching as a new feature, can you please describe the UI behavior a little more and what happen when i click or start typing in the search bar? I'd be happy to discuss and see if we can improve it.
> 
> Thanks! Mohamed
