### ISSUE TITLE
Request to implement Payment solution

### ISSUE THREAD

**Issue by karthikeyana** [mohamedsamara/mern-ecommerce#20]
Hi Mohamed.,
     First of all thanks for your continued contribution to this repository in the pandemic time and your busy work schedule. For this repository, many of them are recognizing and forking to work on further feature implementation to fulfill their business needs and still facing some challenges to implementing features such as payment, Shipment processing, Product search, and filtering, etc out of this Payment Integration is more important than others. If you implement this it would be more helpful to our followers.

- Add a payment method solution to enable checkout and collecting payments
- Associate each Merchant with each brand and payment account 

Dear Followers in this Repository Please raise a hand and thumps up who are all looking for a payment solution 

Thanks.

**Comment by mohamedsamara** [comment]
Hi @karthikeyana,

Thank you for your contribution to this project! I agree about the importance of those features. I'll put each feature into an issue on the repository, that way we can finish them one by one and also to encourage other developers to contribute.

Thanks!

**Comment by karthikeyana** [comment]
Hi @mohamedsamara .,
     Thanks for responding, good idea this will help.
