### ISSUE TITLE
Access to the admin page

### ISSUE THREAD

**Issue by YassineFarih20** [mohamedsamara/mern-ecommerce#208]
after runnig this npm run seed:db [emai-emailexample.com] [password-passwordexample.com], when i want to login to my count i stay on the same page like if the login button doesn't work.

**Comment by hasannasrul** [comment]
Check the console for error. 

it is trying to find the host on localhost:8080 because in .env.example file CLIENT_URL is setup in that way. there you can change the port to 3000 and it will resolve your issue

**Comment by buddhathemanoj** [comment]
@hasannasrul  do you have dummy data for the categories , products , brands , i have added products and categories but its not fetching , but for admin its showing products in dashboard

**Comment by mohamedsamara** [comment]
@YassineFarih20 I'm not sure what errors you see on your end but make sure your database is populated with dummy data. [See guide](https://github.com/mohamedsamara/mern-ecommerce?tab=readme-ov-file#database-seed).
