### ISSUE TITLE
README Documentation to deploy on Vercel

### ISSUE THREAD

**Issue by FedeBatt** [mohamedsamara/mern-ecommerce#214]
Hello, I'm looking for guidance on how to deploy the project on Vercel. I have a project that consists of both a client-side (frontend) and a server-side (backend). I'm wondering if it's advisable to deploy them separately, with the client and server in different folders, or if there's a preferred way to deploy both the client and server together in a unified deployment. Any recommendations or best practices for deploying such projects on Vercel would be greatly appreciated. Thank you!

**Comment by abhishek09827** [comment]
Whether to deploy your client-side and server-side project separately or together on Vercel depends on your priorities. For security and independent scaling, separate deployments are ideal. For simplicity and automatic frontend-backend connection, a unified deployment shines. Consider project size, security needs, and preferred management style when making your choice!

**Comment by mohamedsamara** [comment]
[Vercel deployment guide](https://github.com/mohamedsamara/mern-ecommerce?tab=readme-ov-file#vercel-deployment)
