### ISSUE TITLE
I can't run the project locally

### ISSUE THREAD

**Issue by Danielecarn** [mohamedsamara/mern-ecommerce#216]
**Describe the bug**
I'm trying to follow the README file to run the project but without success.

Is the README file ok?

**To Reproduce**

Mongodb is ok:

![image](https://github.com/mohamedsamara/mern-ecommerce/assets/47640172/b2f98413-239f-4e1f-8972-61f841900656)

But when I write `npm run dev`, I has this error: 

![image](https://github.com/mohamedsamara/mern-ecommerce/assets/47640172/2edb59af-cf57-4d4e-a78f-6dd5661fae08)

When the .env file was inside the server folder, another error was displayed during execution stating that the .env was not found. So I moved it to the root folder.

Could anyone tell me if the application ran in any commit? I would like to do automated tests on the application. Thanks

**Comment by Hitesh-code** [comment]
you have to first install the dotenv 
command : npm i dotenv

**Comment by saoodchoudhary** [comment]
Add .env file in your server folder.

**Comment by YumeLoL** [comment]
have you set up your MongoDB, need to change MONGO_URI to your own.

**Comment by pusty1830** [comment]
command: npm i dotenv and add npm install

**Comment by anishjoshi1999** [comment]
![image](https://github.com/mohamedsamara/mern-ecommerce/assets/38525604/767d5721-99d0-499a-a99f-08f9f904e04a)
![image](https://github.com/mohamedsamara/mern-ecommerce/assets/38525604/8bf736c3-cef5-4d2b-a039-500b71c8df6b)
still getting this error please help

**Comment by mohamedsamara** [comment]
@Danielecarn In the project root run `npm install` and this should install both dependencies for both client and server. See [package.json](https://github.com/mohamedsamara/mern-ecommerce/blob/master/package.json#L10)
