### ISSUE TITLE
Dockerise the application to run the it locally

### ISSUE THREAD

**Issue by creatorshubham** [mohamedsamara/mern-ecommerce#217]
I can see in the comments and the issues section that a lot of users are facing issues while running the project locally.

I would like to contribute to this project by creating a docker compose file using which all the users will be able to run this project locally without having the headache of setting up everything from scratch.

If this feature request gets approved, I would love to work on it right away.

**Comment by mohamedsamara** [comment]
Hey @creatorshubham! Sorry for late reply. Yes! I saw those issues with running the app. Docker compose would be great. Feel free to create a PR and I'll merge it 👍
