### ISSUE TITLE
i am unable to run the client on local

### ISSUE THREAD

**Issue by arman-mondal** [mohamedsamara/mern-ecommerce#218]
![image](https://github.com/mohamedsamara/mern-ecommerce/assets/132995280/fc9e4ed9-114f-4884-ab7a-7956b95c40fc)

**Comment by abhanan369** [comment]
I am having same issue for client

**Comment by arman-mondal** [comment]
> I am having same issue for client

I got the solution,Try to update the modules then try again

**Comment by abhanan369** [comment]
Thanks @arman-mondal 
For me it worked by switching to required node 16.16.0 version as mentioned in package.json file
