### ISSUE TITLE
cant find the port of admin panel 

### ISSUE THREAD

**Issue by erezasmara** [mohamedsamara/mern-ecommerce#220]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anthony0118** [comment]
Hi @erezasmara 
As I am Full Stack Develop who has over 8 years of experience in MERN Stack (Node.js, Express, React), JavaScript and CSS. I have built over 15 websites with Django and implemented a lot of features and enhanced User friendly features with my experinece.
I am really interested on collaborating this project. I hope you have assign this issue to me.
