### ISSUE TITLE
Please help me building the app

### ISSUE THREAD

**Issue by alitasawar** [mohamedsamara/mern-ecommerce#232]
**Describe the bug**
When I make the build by running 

`npm run build`

> Error: Cannot find module 'C:\Users\...\mern-ecommerce\client\node_modules\jimp\dist\index.js'. Please verify that the package.json has a valid "main" entry

Even I tried adding 
main to package.json as following

> {
>   "name": "client",
>   "version": "1.0.0",
>   "description": "MERN Ecommerce Client",
>   "main": "/app/index.js",
>   ...
>   }

but the same error occurred again.

**Screenshots**
![image](https://github.com/mohamedsamara/mern-ecommerce/assets/58731724/d3ca1cee-b257-4c9e-bdba-7cca25165f07)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - NPM Version 16.16.0

**Comment by Notnobcoder** [comment]
Try Remove your node_modules folder and run npm i. Then npm run build
