### ISSUE TITLE
I can't start the client server locally

### ISSUE THREAD

**Issue by ak004** [mohamedsamara/mern-ecommerce#243]
**Describe the bug**
I am trying to run the project locallly and i am having an issue when i am trying to run the frontend code it says something like:
Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported

my node version is v20.11.1
my npm version is 10.2.4
 
![image](https://github.com/user-attachments/assets/f299d4c0-58bd-4f7d-9b47-eb6dabe602fa)

 the backend is working ok i guess
 
![image](https://github.com/user-attachments/assets/12a78965-b1a4-48d4-bfd9-852bbbcd3198)

**Comment by mohamedsamara** [comment]
@ak004 This is an error due to webpack 4 support for node >= 18. It is fixed in a044fa0d4eb336ae1ae4f63dfc99c2e1a5b9282d
