### ISSUE TITLE
On Adding account details, The next step to manage order doesn't get open itself.

### ISSUE THREAD

**Issue by nish0007nish** [mohamedsamara/mern-ecommerce#3]
As a user click save the details. We should take him/her to the next step itself.

![image](https://user-images.githubusercontent.com/64981592/94370633-c3bc4e80-010e-11eb-8cf8-58813679ea98.png)

**Comment by mohamedsamara** [comment]
Hi @nish0007nish ! Thanks for your feedback. I don't think "Account Details" page is related to "Manage Orders" page as steps. There are some scenarios when a user wants to update his/her account details and navigate away to other page, in this case taking him/her to "Manage Orders" page becomes irrelevant.

**Comment by nish0007nish** [comment]
Thanks for confirmation. Closing the issue.
