### ISSUE TITLE
admin area

### ISSUE THREAD

**Issue by ozgurmuraterhan** [mohamedsamara/mern-ecommerce#39]
hi, this is project beatuful. i didn't find admin area on demo link.

tell me admin links or give me example mongo backup.

thanks o lot

**Comment by mohamedsamara** [comment]
@ozgurmuraterhan the admin area appear if you have an admin account, there is a role field for each account. If you run the app locally and have an account created and changed the role field value in user collection to "ROLE_ADMIN", you will be able to see it.

**Comment by ozgurmuraterhan** [comment]
okey :)))
