### ISSUE TITLE
After clear order, website fails to appear.

### ISSUE THREAD

**Issue by talmax1124** [mohamedsamara/mern-ecommerce#44]
After I click cancel order, page turns to full white with no content. Also can you integrate payment with stripe or something like that with sandbox

**Comment by mohamedsamara** [comment]
@talmax1124 We are working on the payment module. Can you please provide a screenshot or anything that will help me reproduce the issue? a screenshot of the browser console when you click cancel order would definitely help. Thanks!

**Comment by talmax1124** [comment]
I have tried once again, and it has functioned
