### ISSUE TITLE
for admin 

### ISSUE THREAD

**Issue by dclambo720** [mohamedsamara/mern-ecommerce#46]
do u have any admin dashboard for this webapp

**Comment by mohamedsamara** [comment]
@dclambo720 the admin area appear if you have an admin account, there is a role field for each account. If you run the app locally and have an account created and changed the role field value in user collection to "ROLE_ADMIN", you will be able to see it.

**Comment by samlovescoding** [comment]
Can you provide demo admin role on demo heroku deployment

**Comment by mohamedsamara** [comment]
@samlovescoding here is an admin [demo](https://mernstore-bucket.s3.us-east-2.amazonaws.com/admin.mp4)
