### ISSUE TITLE
how do i add the base api key, it is showing an error

### ISSUE THREAD

**Issue by bharath2612** [mohamedsamara/mern-ecommerce#47]
<img width="1440" alt="Screenshot 2021-05-07 at 1 29 37 PM" src="https://user-images.githubusercontent.com/42945720/117418003-8cc9d900-af38-11eb-86f1-c2d227b066e4.png">

**Comment by mohamedsamara** [comment]
@bharath2612 Mailchimp keys are missing, these keys are secrets and are not shared between projects. You need to obtain them from your Mailchimp account and put them in the .env file in the project.

**Comment by bharath2612** [comment]
thank you, i will try that :)

**Comment by bharath2612** [comment]
@mohamedsamara how can I add the JWT secret key? I wanted to signup in the website
