### ISSUE TITLE
I cant start de application with token problem

### ISSUE THREAD

**Issue by eduardodiasc** [mohamedsamara/mern-ecommerce#49]
[nodemon] starting `node server`
/Users/eduardocruz/Public/projetos/ecross/server/routes/api/product.js:118
      products: products.filter(item => item?.brand?.isActive === true)
                                             ^

SyntaxError: Unexpected token .

**Comment by karthikeyana** [comment]
Please update nodejs version 

![image](https://user-images.githubusercontent.com/10651426/117561136-afcbc880-b0b1-11eb-975b-9a2c5285f2a6.png)

**Comment by bharath2612** [comment]
@karthikeyana I cannot signup when I try to create the account, can you help?

**Comment by karthikeyana** [comment]
@bharath2612 kindly share the error that you are getting?

**Comment by bharath2612** [comment]
<img width="1440" alt="Screenshot 2021-05-09 at 6 15 52 PM" src="https://user-images.githubusercontent.com/42945720/117572923-cd6d5200-b0f2-11eb-9a0c-4207f4d555e9.png">

**Comment by bharath2612** [comment]
i cannot sign up here..

**Comment by karthikeyana** [comment]
@bharath2612 Yes, you can signup there, if you face any issue. please create a separate thread with the proper error log. 

Thanks.

**Comment by mohamedsamara** [comment]
@eduardodiasc this error is possibly because there are no products data in database. I'll do a fix at my end to avoid it when there is no data. Please add some product data and let me know if you still see the issue.
