### ISSUE TITLE
product's image upload  error

### ISSUE THREAD

**Issue by waseem11011** [mohamedsamara/mern-ecommerce#52]
i am not able to upload image to s3 bucket , product is not not created whenever i attach a image to it. please help

**Comment by mohamedsamara** [comment]
@waseem11011 This might happen if you haven't setup AWS or added these [env](https://github.com/mohamedsamara/mern-ecommerce/blob/master/.env.example#L18) variables in the project. Also, try to log the error on this [line](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/routes/api/product.js#L105).
