### ISSUE TITLE
product can't be uploaded from admin panel

### ISSUE THREAD

**Issue by luqikhan** [mohamedsamara/mern-ecommerce#53]
hello sir, i trying to post product from admin panel but it can't be uploaded and showing me error 400. and also guide me from where i can to admin dashborad..
<img width="900" alt="error" src="https://user-images.githubusercontent.com/44724999/119555812-b8154a80-bdb7-11eb-8813-771093167865.PNG">

**Comment by mohamedsamara** [comment]
@luqikhan Try to log the error on this [line](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/routes/api/product.js#L105) to see the error details and make sure you added AWS [env](https://github.com/mohamedsamara/mern-ecommerce/blob/master/.env.example#L18) variables if you haven't already.
