### ISSUE TITLE
SIGNUP SELL

### ISSUE THREAD

**Issue by devlamine** [mohamedsamara/mern-ecommerce#54]
Hi
how does this page work a success message but I do not receive anything ?
https://mern-store-80202.herokuapp.com/sell

**Comment by mohamedsamara** [comment]
@devlamine an admin will approve or reject the request. Once approved, the user will be sent an email to complete merchant account signup.

**Comment by devlamine** [comment]
Thanks for your quick response, great job . Are you going to add other features in the coming days?

**Comment by mohamedsamara** [comment]
@devlamine I will start working on the [payment module](https://github.com/mohamedsamara/mern-ecommerce#whats-next) soon but because of my schedule I have limited time during the week.
