### ISSUE TITLE
Wishlist and Cart Items get retain from my previous account when I create a new account.

### ISSUE THREAD

**Issue by smartupnish** [mohamedsamara/mern-ecommerce#58]
Wishlist and cart item get retain from my previous account when I create a new account.

**Steps to reproduce**

1. Login with your existing account
2. Add few products to your wishlist and cart
![image](https://user-images.githubusercontent.com/64981592/122515720-b3147700-cfc2-11eb-8be3-f885cea962c6.png)
3. logout the account and create another account.
![image](https://user-images.githubusercontent.com/64981592/122515880-e951f680-cfc2-11eb-865c-1ab4600669a6.png)
4. Verify that account is created
![image](https://user-images.githubusercontent.com/64981592/122516075-274f1a80-cfc3-11eb-8e40-29757a984342.png)
5. Click on the wishlist tab of the dashboard.
![image](https://user-images.githubusercontent.com/64981592/122516146-3e8e0800-cfc3-11eb-8869-ac4ec085b9ab.png)
6. Verify the wishlist item and cart item.
![image](https://user-images.githubusercontent.com/64981592/122516251-64b3a800-cfc3-11eb-88da-413492dc72e0.png)
![image](https://user-images.githubusercontent.com/64981592/122518675-5c10a100-cfc6-11eb-9768-f2fa39b885f9.png)

**Expected**: Wishlist and cart should be empty after creating the new account
**Actual** Wishlist and cart item get retain items from the previous account.

**Comment by nish0007nish** [comment]
Hi Samara,

I open the bug, It seems like we are getting wishlist and cart items from the unique IP of the device that matches this case. While creating another new account on the same device. It should be considered as the new person. As it can create a privacy problem for a user that shows the list of the item he/she adds to a wishlist or cart.

As per my conclusion: We should not add any item to the cart and wishlist after creating an account. We should consider without login wishlist and cart as an anonymous entity and all-new created account as another known entity.

**Comment by mohamedsamara** [comment]
@nish0007nish This should not retain both items for new accounts. I'll look into it. Did you signup through Google/Facebook providers for the other account?

**Comment by nish0007nish** [comment]
@mohamedsamara Yes, the first time I logged in using google. Then, I created a different account with a different email ID.

**Comment by mohamedsamara** [comment]
@smartupnish The wishlist items is fixed. For the current cart implementation I can't find a reason to clear out the cart when the user switches accounts because they will lose it considering (the cart is not maintained on the server and is handled on the browser), cart is sent to the server only when the user places an order.
