### ISSUE TITLE
There is an unnecessary gap between user review and add review

### ISSUE THREAD

**Issue by nish0007nish** [mohamedsamara/mern-ecommerce#59]
There is an unnecessary gap between user review and add review

![image](https://user-images.githubusercontent.com/64981592/122519996-f6bdaf80-cfc7-11eb-95a2-5f94d8e1799b.png)

**Expected** There should not be an unnecessary gap between user review and add review
**Actual** there is a huge gap between both user review and add review

**Comment by nish0007nish** [comment]
It is when only one review is added by the user and no other review is there

**Comment by mohamedsamara** [comment]
@nish0007nish thanks for reporting. Yes I see it. Will add a fix.
