### ISSUE TITLE
Incorrect calculation of tax shown on the order summary when the user places an order with multiple items or more than 1 quantity

### ISSUE THREAD

**Issue by nish0007nish** [mohamedsamara/mern-ecommerce#60]
Incorrect calculations of tax shown on the order summary when the user places an order with multiple items or more than 1 quantity.

**Steps to reproduce**

1. User opens a product page and adds more than 1 quantity.
2. User clicks on add to cart button.
3.  The user opens another product page and adds that product to the cart.
4. User clicks on "Place Order" and "Your Order" list will open.
5. User clicks on the order to see the summary.
6. Verify the tax on the order is calculated.

**Actual**: A static tax is calculated at the order level.
**Expected** Tax should be calculated on the item level and their quality based on cost.

![image](https://user-images.githubusercontent.com/64981592/122684097-5d092480-d1b8-11eb-9f2a-93de0086d1cb.png)

**Comment by mohamedsamara** [comment]
@nish0007nish thank you for reporting this issue. I agree, this must be calculated for each item quantity.

**Comment by nish0007nish** [comment]
@mohamedsamara As per my investigation on bug #63 , It seems like this feature requires a short modification at the quantity level. 

Look, When both items are ordered with a single quantity then tax calculation works fine.
![image](https://user-images.githubusercontent.com/64981592/122704692-0b3cba80-d209-11eb-89b3-9e04c5c5033c.png)
but when the quantity is increased and ordered with more than 1 quantity then the calculation works like a single quantity.
![image](https://user-images.githubusercontent.com/64981592/122704825-53f47380-d209-11eb-864f-045fd7576f48.png)

One more modification should be there before placing the order and go through the payments. The user must be aware of the total cost after tax, shipping, and other extra charges. Hopefully, You may work on it in the coming functionality.
 or you can add the total price here in the below screenshot.
 
![image](https://user-images.githubusercontent.com/64981592/122707327-abe1a900-d20e-11eb-8c56-4cf8ee673a78.png)

**Comment by mohamedsamara** [comment]
@smartupnish this will be fixed when deploying to production.
