### ISSUE TITLE
Where to find Customer Orders in Admin Dashboard and change its status

### ISSUE THREAD

**Issue by rajkeshri77** [mohamedsamara/mern-ecommerce#70]
Hi,

I am not able to see customers orders in Admin or Merchant Dashboard. Is there any way to see pending orders of customer and change it status?

**Comment by mohamedsamara** [comment]
@rajkeshri77 it is in development at the moment. It will be in production next week.

**Comment by rajkeshri77** [comment]
Okay, Thanks!!
