### ISSUE TITLE
Admin Order details

### ISSUE THREAD

**Issue by vishalsharma1505** [mohamedsamara/mern-ecommerce#71]
from user prospective , If I've ordered some item and i can see that on orders but from admin/merchant prospective, i'm unable to see what user has ordered for him/her and also where can i see the contact us details data?
Thanks in advance!

**Comment by mohamedsamara** [comment]
@vishalsharma1505 yes both customer orders and contact us features are in development at the moment. I would say they will be in production next week.

**Comment by vishalsharma1505** [comment]
@mohamedsamara oh , thanks mate :)
