### ISSUE TITLE
Order details

### ISSUE THREAD

**Issue by vishalsharma1505** [mohamedsamara/mern-ecommerce#74]
Hi There ,

First of all thank you for putting this website on GitHub , this is really helpful :)

Well my issue is that i can't see all orders at a time , i have to manually search the orders from the order id and even I've to get that order id from user dashboard.

Thanks in advance!

**Comment by mohamedsamara** [comment]
@vishalsharma1505 There is a lot of orders data to display. I think implementing pagination might work just fine for now.

**Comment by vishalsharma1505** [comment]
> @vishalsharma1505 There is a lot of orders data to display. I think implementing pagination might work just fine for now.

Actually i'm not bale to see single order , i've to mainly search them all.

**Comment by mohamedsamara** [comment]
@vishalsharma1505 Yes, orders are not displayed now. This is why I added the search part of the solution. It will be time expensive to retrieve all orders data from the server and rendering them on the frontend. I'm looking to implement pagination where admin can view(paginate) through all orders and maybe filtering and sorting in the future.
