### ISSUE TITLE
ValidationError: Can't run the project locally

### ISSUE THREAD

**Issue by phanindra-max** [mohamedsamara/mern-ecommerce#75]
I've cloned the repo and added those API keys as said in the documentation.

But the application doesn't seem to run and showing me this error:
![image](https://user-images.githubusercontent.com/51989959/125652432-02040c51-f50c-4e72-a74a-b3b787ef647b.png)

can someone tell me where am I going wrong?

**Comment by phanindra-max** [comment]
Okay just found what causes the problem

The issues arise due to breaking changes in webpack new version 
[Stackoverflow](https://stackoverflow.com/a/62680933/13181329)

**Comment by phanindra-max** [comment]
Now that the previous error is gone, another comes up due to these breaking changes.

So are you @mohamedsamara interested in updating this for the new version? I hope you do. 

If you're interested I'll fix these new update-related issues and raise a pull request. Is that fine?

**Comment by mohamedsamara** [comment]
@phanindra-max sure! feel free to make a PR and I'll check it and merge.
