### ISSUE TITLE
npm start error 

### ISSUE THREAD

**Issue by ajithv11** [mohamedsamara/mern-ecommerce#76]
I am getting the following error when I tried to start the application

mern-ecommerce/server/routes/api/product.js:292
    if (!productDoc || productDoc?.brand?.isActive === false) {                        
SyntaxError: Unexpected token '.'

Could you please help me. 

Also help me in migrating the mongo db data to my local system

**Comment by himanshujaidka** [comment]
to migrate the db, @ajithv11 go to .env file and replace the `MONGO_URI=mongodb://localhost:27017/YourDBName`

**Comment by ajithv11** [comment]
What about the error i have mentioned in the first post, I could not get rid of that

**Comment by himanshujaidka** [comment]
> What about the error i have mentioned in the first post, I could not get rid of that

pls provide some more details

**Comment by himanshujaidka** [comment]
@ajithv11 refer to this https://github.com/mohamedsamara/mern-ecommerce/issues/49

**Comment by mohamedsamara** [comment]
@ajithv11 I was wondering if you still get the error after you have set up the database or if there are any database errors before this error?
