### ISSUE TITLE
Error: Unknown authentication strategy "jwt"

### ISSUE THREAD

**Issue by himanshujaidka** [mohamedsamara/mern-ecommerce#78]
after sign-in, and willing to perform various actions but this error will not allow me to perform.

**Comment by mohamedsamara** [comment]
@himanshujaidka can you please send a screenshot of the error? Is it showing in the terminal? This sounds like jwt or passport module is not imported.

**Comment by himanshujaidka** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/58654018/127693529-6ae86e67-12fc-451b-92f6-53da92567670.png)

**Comment by himanshujaidka** [comment]
I have import this modules again

**Comment by mohamedsamara** [comment]
@himanshujaidka It look like the passport configuration file isn't injected in the server entry file. Do you see the error even with this [line](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/index.js#L39) there? Can you please share the steps to reproduce it, what page, what action or api you are trying to call?

**Comment by himanshujaidka** [comment]
when I am calling any API even if it is signing API or signup this error is reproduced. for example when I am creating the user every time this error occurs in the network window

**Comment by himanshujaidka** [comment]
> @himanshujaidka It look like the passport configuration file isn't injected in the server entry file. Do you see the error even with this [line](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/index.js#L39) there? Can you please share the steps to reproduce it, what page, what action or api you are trying to call?

@mohamedsamara thanks sir, actually I have commented out the file inside `config/passport` 😅 for some reason and forgot to uncomment that.
