### ISSUE TITLE
The User is unable to search orders with orderID after completing the order placement process.

### ISSUE THREAD

**Issue by smartupnish** [mohamedsamara/mern-ecommerce#79]
The user is unable to search orders with orderID after completing the order placement process.

**Steps to reproduce**
1. User adds any product to the cart.
![image](https://user-images.githubusercontent.com/64981592/126909167-31a906a0-e538-4fa4-b808-e5586a49939a.png)
2. User clicks on "Place Order" and copy the orderID.
![image](https://user-images.githubusercontent.com/64981592/126909198-bf7c571e-bc9e-40e9-a952-c51ff5de6e6d.png)
3. User clicks on manage order and searches the order by entering copied orderID while placing the order.
![image](https://user-images.githubusercontent.com/64981592/126909249-c8b4cf2c-6a08-4e39-a1eb-07f275accac1.png)
4. On clicking search verify the list of orders in the search result.
![image](https://user-images.githubusercontent.com/64981592/126909323-1afcfb58-3da7-4548-8a54-15de12e51f5f.png)

**Expected** List of all orders (Combined with orderID) should appear in the search result.
**Actual** Nothing is shown on the search result.

**Comment by mohamedsamara** [comment]
@smartupnish Does the order show in the list before typing in the search?

**Comment by smartupnish** [comment]
@mohamedsamara No, It doesn't show in the list as well before typing in search.

**Comment by mohamedsamara** [comment]
@smartupnish I know from the order id that the order was created but just to double check can you please check if it is in the database in case this page with success order is not an old order that was deleted. Also I'm curious if you see the order when you go to the order page /order/[orderID].

**Comment by mohamedsamara** [comment]
Hi @smartupnish! Sure send me a message on [LinkedIn](https://www.linkedin.com/in/mohamed-samara/) and will go over those issues.
