### ISSUE TITLE
my questions related to project and structure

### ISSUE THREAD

**Issue by shivamm112** [mohamedsamara/mern-ecommerce#85]
I just tested this project and it's really well setup. Just amazing! I wanted to ask a few questions as I couldn't find it online. I am a junior developer so I wanted to level up.

1. I saw that you structured it really well, the redux part and everything. But I did not understand, why didn't you keep the client and server fully separate? As I can see the dependencies for both server and client are both in the same `package.json` and there a few other places in the root where you have have configured it so that it could work nicely. I have made quite a number of applications but I haven't used that practice. a. Can you tell me why did you go for that? b. What are the best practices to go about this and industry standards in big production level applications?

2. If someone had to deploy this to AWS which requires server and client to be separate like a lot of other sites, how should one go about segregating it fully and deploy it to AWS EC2? I just want to know the process as a developer.

3. I don't have enough practice with webpack and other super important packages and it's usage. Can you suggest some resources so that I can become more proficient.

Let me know wherever I am wrong or if my knowledge or assumptions about anything is wrong. Feel free to answer these whenever you are free. If someone else feels that they have strong (and right) knowledge about this, go ahead and reply, just mention the ques number with it for better reference.

Thanks again! @mohamedsamara

**Comment by mohamedsamara** [comment]
Hi @shivamm112! I'm glad you like the project! 

Q1: I didn't have any reason to separate both client and server any further, I saw this practice online and tried it in this example and I tried to use the shared configuration as much as i could. However, there is a lot of updates about code structure and best practices now, like for example SSR, SSG with Next.js and Gatsby so these are the industry standards recently.

Q2: I haven't tried to deploy it to AWS but i don't think it needs more separation to be deployed. 

Q3: There is some tutorials on youtube that explains everything you need about webpack configurations. Check freecodecamp tutorial on webpack. 

I hope this answers your questions.
