### ISSUE TITLE
AWS Alternatives.

### ISSUE THREAD

**Issue by Mugerwa-Joseph** [mohamedsamara/mern-ecommerce#88]
What alternatives would you suggest instead of AWS, 

Thanks for the massive efforts invested into the project.

**Comment by mohamedsamara** [comment]
Thank you @Mugerwa-Joseph! There is quite few alternatives to AWS out there like Google Cloud Storage and Azure but since the project is using AWS S3 only to save images I would suggest something like [cloudinary](https://cloudinary.com/documentation/node_image_and_video_upload#server_side_upload).

**Comment by Mugerwa-Joseph** [comment]
Thanks @mohamedsamara 
Your time and efforts are highly appreciated.
